'use strict';

module.exports = async () => [
  'Metarhia Technology Stack Key Ideas:',
  '• Unification: API, data, contracts',
  '• Homogeneity of server infrastructure',
  '• No back compatibility (no legacy support)',
  '• Open Source & no vendor lock',
  '• Architectural decisions (single plan)',
  '• Community and trainings',
  '',
  'Impress Application Server',
  'for highload clusters and private clouds with Node.js',
  'https://github.com/metarhia/impress',
  '',
  'JSTP protocol',
  'RPC, event bus, db sync on TCP, TLS, WebSocket and JSON5;',
  'with SDK for mobile and desktop: JavaScript, Java, Swift,',
  'C++, Haskell, Python, Objective-C, PHP, Golang, C#',
  'https://github.com/metarhia/jstp',
  '',
  'GlobalStorage',
  'Distributed reactive in-memory DBMS, work in progress',
  'https://github.com/metarhia/globalstorage',
  '',
  'Metasync: asynchronous programming abstractions',
  'https://github.com/metarhia/metasync',
  '',
  'Maojian: testing framework',
  'https://github.com/metarhia/maojian',
];
